version: '2'
services:
  database:
    image: postgres
    environment:
      POSTGRES_ASSWORD: 'testpassword'
      POSTGRES_USER: 'vuser'
      POSTGRES_DB: 'sqlalchemy'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./db-volume/postgre:/var/lib/postgresql/data
